<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_LearnOrgPassword</name>
   <tag></tag>
   <elementGuidId>1b90fef5-4c67-4e26-8500-cf837ae839be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;LearnOrgPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='LearnOrgPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;LearnOrgPassword&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97c3b62c-f3ef-4319-9f73-24c47f8fa9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>84bb1900-a0be-4d54-a708-a9ee0ae272d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LearnOrgPassword</value>
      <webElementGuid>ba29ad7e-c9cb-4011-8a9a-930e59c15384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>702eaebf-e712-4994-91db-362e02007e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>03010967-6559-4f97-a090-0e324d5ff40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layer8&quot;)/table[1]/tbody[1]/tr[2]/td[1]/table[@class=&quot;bodytext&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;inputText&quot;]</value>
      <webElementGuid>9fd7178b-2d1d-482f-8274-6bd2323a6343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='LearnOrgPassword']</value>
      <webElementGuid>6ea3ccde-51f9-486c-9ef2-e861a5df5d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Layer8']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>81d8ffd9-7c62-4ff9-895a-48ac3cb1a215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>36ab62ea-e758-472e-8c9e-84684e7309c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'LearnOrgPassword']</value>
      <webElementGuid>ea2a2ea4-6386-4d40-aef3-4f82d039bcfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
