<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_LearnOrgUsername</name>
   <tag></tag>
   <elementGuidId>d104d316-bb35-4934-995b-e70f2b5fc61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;LearnOrgUsername&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='LearnOrgUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;LearnOrgUsername&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9892edc-75c5-4903-9965-e1ccb8654738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04f267f4-be50-4da5-afc0-e5b8fbbe2eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LearnOrgUsername</value>
      <webElementGuid>ee14e27f-22a1-47ec-98df-a66b36d891fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>3df8cc71-6c6c-4011-b08f-d81ad08d45c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>37d405c3-7d6c-4648-91d7-17d4d82d7ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layer8&quot;)/table[1]/tbody[1]/tr[2]/td[1]/table[@class=&quot;bodytext&quot;]/tbody[1]/tr[1]/td[2]/input[@class=&quot;inputText&quot;]</value>
      <webElementGuid>02f98a36-e24c-40e8-aeca-c58f27311aad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='LearnOrgUsername']</value>
      <webElementGuid>fa241ae6-0d7a-4525-a241-307407c10b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Layer8']/table/tbody/tr[2]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6ef20cd3-5a1e-449a-8518-bfa34791a0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>caa3eb30-24f8-4269-800e-0ed9506ca954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'LearnOrgUsername']</value>
      <webElementGuid>3cbf4d47-bbfc-44e1-a19b-c412726c335d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
